spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flickmatch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    senderEmail: "foo@gmail.com"
    host: smtp.gmail.com
    port: 587
    username: flickmatch-api
    password: zttpycdlhrubjlst
    smtp:
      auth: true
      starttls:
        enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
config:
  SECRET_KEY: c7968315550171100df07375129e6a2e1f87defda3dceb5f56103ddb43b5d1df009d157d109aec24fb8481d207baadc41f837a02b3946f82c4d6098abd33d01a